name: mydosen
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  intl: ^0.20.2
  get_it: ^9.0.5
  dartz: ^0.10.1
  flutter_osm_plugin: ^1.4.2
  shimmer: ^3.0.0
  shared_preferences: ^2.5.3
  flutter_animate: ^4.5.2
  flutter_dotenv: ^6.0.0
  package_info_plus: ^9.0.0
  flutter_secure_storage: ^9.2.2
  socket_io_client: ^2.0.3+1
  geolocator: ^13.0.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  provider: ^6.1.2
  flutter_background_service: ^5.0.10
  flutter_local_notifications: ^18.0.1

dependency_overrides:
  collection: 1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/icon-full.png
    - .env
